' CodeGenerator — writes a complete VB.NET + Terminal.Gui project to outputDir.
' One method per output file; string templates are used for clarity.
Imports System.IO
Imports System.Text
Imports System.Collections.Generic


    Public Class CodeGenerator

        ''' <summary>Generate the full project into outputDir, creating it if needed.</summary>
        Public Sub GenerateProject(doc As DslDocument, outputDir As String)
            Directory.CreateDirectory(outputDir)

            ' Derive a safe project name from the directory name
            Dim projName = MakeSafeName(Path.GetFileName(outputDir.TrimEnd(Path.DirectorySeparatorChar)))
            If String.IsNullOrEmpty(projName) Then projName = "DataEntryApp"

            WriteProjectFile(outputDir, projName)
            WriteProgram(outputDir, projName, doc)
            WriteDataFile(outputDir, projName, doc)
            WriteFormatHelper(outputDir, projName)
            WriteColorHelper(outputDir, projName)
            WriteMainForm(outputDir, projName, doc)
            WriteValidationStubs(outputDir, projName, doc)
        End Sub

        ' ── .vbproj ──────────────────────────────────────────────────────────

        Private Sub WriteProjectFile(dir As String, name As String)
            Dim sb As New StringBuilder
            sb.AppendLine("<Project Sdk=""Microsoft.NET.Sdk"">")
            sb.AppendLine("  <PropertyGroup>")
            sb.AppendLine("    <OutputType>Exe</OutputType>")
            sb.AppendLine($"    <RootNamespace>{name}</RootNamespace>")
            sb.AppendLine("    <TargetFramework>net10.0</TargetFramework>")
            sb.AppendLine("    <PublishSingleFile>true</PublishSingleFile>")
            sb.AppendLine("    <SelfContained>true</SelfContained>")
            sb.AppendLine("    <InvariantGlobalization>true</InvariantGlobalization>")
            sb.AppendLine("    <SuppressTrimAnalysisWarnings>true</SuppressTrimAnalysisWarnings>")
            sb.AppendLine("  </PropertyGroup>")
            sb.AppendLine("  <ItemGroup>")
            sb.AppendLine("    <PackageReference Include=""Terminal.Gui"" Version=""2.4.17"" />")
            sb.AppendLine("  </ItemGroup>")
            sb.AppendLine("</Project>")
            Write(dir, $"{name}.vbproj", sb)
        End Sub


        ' ── Program.vb ───────────────────────────────────────────────────────

        Private Sub WriteProgram(dir As String, ns As String, doc As DslDocument)
            Dim sb As New StringBuilder
            sb.AppendLine($"' Generated by DataEntry compiler.")
            sb.AppendLine($"Imports Terminal.Gui.App")
            sb.AppendLine()
            sb.AppendLine($"Namespace {ns}")
            sb.AppendLine($"    Module Program")
            sb.AppendLine($"        Sub Main(args As String())")
            sb.AppendLine($"            Dim app = Application.Create().Init()")
            sb.AppendLine($"            Dim form As New MainForm(app)")
            sb.AppendLine($"            app.Run(form, Nothing)")
            sb.AppendLine($"            app.Dispose()")
            sb.AppendLine($"        End Sub")
            sb.AppendLine($"    End Module")
            sb.AppendLine($"End Namespace")
            Write(dir, "Program.vb", sb)
        End Sub

        ' ── DataFile.vb ──────────────────────────────────────────────────────

        Private Sub WriteDataFile(dir As String, ns As String, doc As DslDocument)
            Dim ds = doc.Data
            Dim lend = LineEndingString(ds.Ending)
            Dim isAppend = (ds.Mode = AppendMode.Append)

            Dim sb As New StringBuilder
            sb.AppendLine($"' DataFile — handles reading and writing fixed-length records.")
            sb.AppendLine("Imports System.IO")
            sb.AppendLine("Imports System.Text")
            sb.AppendLine()
            sb.AppendLine($"Namespace {ns}")
            sb.AppendLine("    Public Class DataFile")
            sb.AppendLine($"        Private Const FilePath As String = ""{EscapeString(ds.FilePath)}""")
            sb.AppendLine($"        Private Const Lrecl As Integer = {ds.Lrecl}")
            sb.AppendLine($"        Private Const IsAppend As Boolean = {isAppend.ToString().ToLower()}")
            sb.AppendLine()
            sb.AppendLine("        ' Write a record to the file.")
            sb.AppendLine("        Public Shared Sub WriteRecord(data As String)")
            sb.AppendLine("            ' Pad or truncate to LRECL")
            sb.AppendLine("            If data.Length < Lrecl Then data = data.PadRight(Lrecl)")
            sb.AppendLine("            If data.Length > Lrecl Then data = data.Substring(0, Lrecl)")
            sb.AppendLine($"            Dim lineEnd As String = ""{lend}""")
            sb.AppendLine("            Using sw As New StreamWriter(FilePath, IsAppend, Encoding.ASCII)")
            sb.AppendLine("                sw.Write(data)")
            sb.AppendLine("                If lineEnd.Length > 0 Then sw.Write(lineEnd)")
            sb.AppendLine("            End Using")
            sb.AppendLine("        End Sub")
            sb.AppendLine()
            sb.AppendLine("        ' Read all records from the file into a List.")
            sb.AppendLine("        Public Shared Function ReadAllRecords() As List(Of String)")
            sb.AppendLine("            Dim records As New List(Of String)")
            sb.AppendLine("            If Not File.Exists(FilePath) Then Return records")
            sb.AppendLine("            Dim raw = File.ReadAllBytes(FilePath)")
            sb.AppendLine($"            Dim recSize = Lrecl + ""{lend}"".Length")
            sb.AppendLine("            Dim i = 0")
            sb.AppendLine("            Do While i + Lrecl <= raw.Length")
            sb.AppendLine("                records.Add(Encoding.ASCII.GetString(raw, i, Lrecl))")
            sb.AppendLine("                i += recSize")
            sb.AppendLine("            Loop")
            sb.AppendLine("            Return records")
            sb.AppendLine("        End Function")
            sb.AppendLine("    End Class")
            sb.AppendLine("End Namespace")
            Write(dir, "DataFile.vb", sb)
        End Sub

        ' ── FormatHelper.vb ──────────────────────────────────────────────────

        Private Sub WriteFormatHelper(dir As String, ns As String)
            Dim sb As New StringBuilder
            sb.AppendLine("' FormatHelper — applies FORMAT mask rules to field values.")
            sb.AppendLine("Imports System.Text")
            sb.AppendLine()
            sb.AppendLine($"Namespace {ns}")
            sb.AppendLine("    Public Module FormatHelper")
            sb.AppendLine()
            sb.AppendLine("        ' Apply a FORMAT mask to a raw input string.")
            sb.AppendLine("        ' Returns the formatted string padded/trimmed to fieldLen.")
            sb.AppendLine("        Public Function ApplyMask(raw As String, mask As String,")
            sb.AppendLine("                                  fieldLen As Integer,")
            sb.AppendLine("                                  isNumeric As Boolean) As String")
            sb.AppendLine("            Dim sb As New StringBuilder")
            sb.AppendLine("            Dim ri = 0  ' index into raw input")
            sb.AppendLine("            For Each mc In mask")
            sb.AppendLine("                Select Case mc")
            sb.AppendLine("                    Case ""X""c  ' alphanumeric — take as-is")
            sb.AppendLine("                        sb.Append(If(ri < raw.Length, raw(ri), "" ""c))")
            sb.AppendLine("                        ri += 1")
            sb.AppendLine("                    Case ""U""c  ' upper case")
            sb.AppendLine("                        sb.Append(If(ri < raw.Length, Char.ToUpperInvariant(raw(ri)), "" ""c))")
            sb.AppendLine("                        ri += 1")
            sb.AppendLine("                    Case ""L""c  ' lower case")
            sb.AppendLine("                        sb.Append(If(ri < raw.Length, Char.ToLowerInvariant(raw(ri)), "" ""c))")
            sb.AppendLine("                        ri += 1")
            sb.AppendLine("                    Case ""9""c  ' digit")
            sb.AppendLine("                        Dim dc = If(ri < raw.Length, raw(ri), "" ""c)")
            sb.AppendLine("                        sb.Append(If(Char.IsDigit(dc), dc, "" ""c))")
            sb.AppendLine("                        ri += 1")
            sb.AppendLine("                    Case ""Z""c  ' zero-fill digit")
            sb.AppendLine("                        Dim dc = If(ri < raw.Length, raw(ri), ""0""c)")
            sb.AppendLine("                        sb.Append(If(Char.IsDigit(dc), dc, ""0""c))")
            sb.AppendLine("                        ri += 1")
            sb.AppendLine("                    Case Else   ' literal character")
            sb.AppendLine("                        sb.Append(mc)")
            sb.AppendLine("                End Select")
            sb.AppendLine("            Next")
            sb.AppendLine("            Dim result = sb.ToString()")
            sb.AppendLine("            ' Adjust to fieldLen: numbers right-adjust, text left-adjust")
            sb.AppendLine("            If result.Length < fieldLen Then")
            sb.AppendLine("                result = If(isNumeric, result.PadLeft(fieldLen), result.PadRight(fieldLen))")
            sb.AppendLine("            ElseIf result.Length > fieldLen Then")
            sb.AppendLine("                result = result.Substring(0, fieldLen)")
            sb.AppendLine("            End If")
            sb.AppendLine("            Return result")
            sb.AppendLine("        End Function")
            sb.AppendLine()
            sb.AppendLine("        ' Returns True if a mask is purely numeric (9 and Z characters only).")
            sb.AppendLine("        Public Function IsNumericMask(mask As String) As Boolean")
            sb.AppendLine("            For Each c In mask")
            sb.AppendLine("                If c <> ""9""c AndAlso c <> ""Z""c Then Return False")
            sb.AppendLine("            Next")
            sb.AppendLine("            Return mask.Length > 0")
            sb.AppendLine("        End Function")
            sb.AppendLine()
            sb.AppendLine("    End Module")
            sb.AppendLine("End Namespace")
            Write(dir, "FormatHelper.vb", sb)
        End Sub

        ' ── ColorHelper.vb (copy into generated project) ─────────────────────

        Private Sub WriteColorHelper(dir As String, ns As String)
            ' We regenerate a self-contained copy so the output project is stand-alone.
            Dim sb As New StringBuilder
            sb.AppendLine("' ColorHelper — maps color name strings to Terminal.Gui ColorName16.")
            sb.AppendLine("Imports Terminal.Gui.Drawing")
            sb.AppendLine()
            sb.AppendLine($"Namespace {ns}")
            sb.AppendLine("    Public Module ColorHelper")
            sb.AppendLine("        Public Function ToColorName16(name As String) As ColorName16")
            sb.AppendLine("            Select Case name.Trim().ToLowerInvariant()")
            sb.AppendLine("                Case ""black""        : Return ColorName16.Black")
            sb.AppendLine("                Case ""darkred"", ""red""  : Return ColorName16.Red")
            sb.AppendLine("                Case ""darkgreen"", ""green"" : Return ColorName16.Green")
            sb.AppendLine("                Case ""darkyellow"", ""yellow"" : Return ColorName16.Yellow")
            sb.AppendLine("                Case ""darkblue"", ""blue"" : Return ColorName16.Blue")
            sb.AppendLine("                Case ""darkmagenta"", ""magenta"" : Return ColorName16.Magenta")
            sb.AppendLine("                Case ""darkcyan"", ""cyan"" : Return ColorName16.Cyan")
            sb.AppendLine("                Case ""gray""         : Return ColorName16.Gray")
            sb.AppendLine("                Case ""darkgray""     : Return ColorName16.DarkGray")
            sb.AppendLine("                Case ""white""        : Return ColorName16.White")
            sb.AppendLine("                Case Else            : Return ColorName16.Gray")
            sb.AppendLine("            End Select")
            sb.AppendLine("        End Function")
            sb.AppendLine()
            sb.AppendLine("        Public Function MakeAttr(fg As String, bg As String) As Attribute")
            sb.AppendLine("            Return New Attribute(ToColorName16(fg), ToColorName16(bg))")
            sb.AppendLine("        End Function")
            sb.AppendLine("    End Module")
            sb.AppendLine("End Namespace")
            Write(dir, "ColorHelper.vb", sb)
        End Sub

        ' ── MainForm.vb ──────────────────────────────────────────────────────

        Private Sub WriteMainForm(dir As String, ns As String, doc As DslDocument)
            Dim sb As New StringBuilder
            sb.AppendLine("' MainForm — the generated data-entry form.")
            sb.AppendLine("Imports Terminal.Gui.App")
            sb.AppendLine("Imports Terminal.Gui.Views")
            sb.AppendLine("Imports Terminal.Gui.Drawing")
            sb.AppendLine("Imports Terminal.Gui.Input")
            sb.AppendLine("Imports Terminal.Gui.ViewBase")
            sb.AppendLine("Imports System.Collections.Generic")
            sb.AppendLine("Imports TPos = Terminal.Gui.ViewBase.Pos")
            sb.AppendLine("Imports TDim = Terminal.Gui.ViewBase.Dim")
            sb.AppendLine()
            sb.AppendLine($"Namespace {ns}")
            sb.AppendLine("    Public Class MainForm")
            sb.AppendLine("        Inherits Window")
            sb.AppendLine()

            ' One field per screen field — collect all fields across all screens
            Dim fieldVars As New List(Of String)
            For Each scr In doc.Screens
                For i = 0 To scr.Fields.Count - 1
                    Dim varName = $"_{MakeSafeName(scr.Name)}_{i}"
                    fieldVars.Add(varName)
                    sb.AppendLine($"        Private {varName} As TextField")
                Next
            Next

            sb.AppendLine()
            sb.AppendLine("        Private _app As IApplication")
            sb.AppendLine("        Private _recordIndex As Integer = -1")
            sb.AppendLine("        Private _records As List(Of String)")
            sb.AppendLine()
            sb.AppendLine("        Public Sub New(app As IApplication)")
            sb.AppendLine("            _app = app")
            sb.AppendLine("            _records = DataFile.ReadAllRecords()")
            sb.AppendLine("            BuildForm()")
            sb.AppendLine("        End Sub")
            sb.AppendLine()
            sb.AppendLine("        Private Sub BuildForm()")

            ' Screen layout
            Dim varIdx = 0
            For Each scr In doc.Screens
                Dim nfgScr = scr.DefaultColor.Fg
                Dim nbgScr = scr.DefaultColor.Bg
                sb.AppendLine($"            ' Screen: {scr.Name}")
                sb.AppendLine($"            Me.Title = ""{EscapeString(scr.Name)}""")
                sb.AppendLine($"            Me.SetScheme(New Scheme With {{")
                sb.AppendLine($"                .Normal    = ColorHelper.MakeAttr(""{nfgScr}"", ""{nbgScr}""),")
                sb.AppendLine($"                .Focus     = ColorHelper.MakeAttr(""Black"", ""Cyan""),")
                sb.AppendLine($"                .Editable  = ColorHelper.MakeAttr(""Black"", ""Cyan""),")
                sb.AppendLine($"                .HotNormal = ColorHelper.MakeAttr(""{nfgScr}"", ""{nbgScr}""),")
                sb.AppendLine($"                .HotFocus  = ColorHelper.MakeAttr(""Black"", ""Cyan"")")
                sb.AppendLine($"            }})")
                sb.AppendLine()

                For Each sfld In scr.Fields
                    Dim vn = fieldVars(varIdx)
                    varIdx += 1
                    Dim nfg = If(sfld.NormalColor IsNot Nothing, sfld.NormalColor.Fg, scr.DefaultColor.Fg)
                    Dim nbg = If(sfld.NormalColor IsNot Nothing, sfld.NormalColor.Bg, scr.DefaultColor.Bg)
                    Dim ffg = If(sfld.FocusColor IsNot Nothing, sfld.FocusColor.Fg, "Black")
                    Dim fbg = If(sfld.FocusColor IsNot Nothing, sfld.FocusColor.Bg, "Cyan")

                    sb.AppendLine($"            ' Field: {sfld.Label}")
                    Dim lbl_x = sfld.Col - 1
                    Dim lbl_y = sfld.Row
                    Dim tf_x  = sfld.Col - 1 + sfld.Label.Length + 2
                    sb.AppendLine($"            Dim lbl_{vn.TrimStart("_"c)} As New Label()")
                    sb.AppendLine($"            lbl_{vn.TrimStart("_"c)}.Text  = ""{EscapeString(sfld.Label)}:""")
                    sb.AppendLine($"            lbl_{vn.TrimStart("_"c)}.X     = TPos.Absolute({lbl_x})")
                    sb.AppendLine($"            lbl_{vn.TrimStart("_"c)}.Y     = TPos.Absolute({lbl_y})")
                    sb.AppendLine($"            lbl_{vn.TrimStart("_"c)}.Width = TDim.Absolute({sfld.Label.Length + 1})")
                    sb.AppendLine($"            Me.Add(lbl_{vn.TrimStart("_"c)})")
                    sb.AppendLine($"            {vn} = New TextField()")
                    sb.AppendLine($"            {vn}.X     = TPos.Absolute({tf_x})")
                    sb.AppendLine($"            {vn}.Y     = TPos.Absolute({lbl_y})")
                    sb.AppendLine($"            {vn}.Width = TDim.Absolute({sfld.Len})")
                    sb.AppendLine($"            {vn}.SetScheme(New Scheme With {{")
                    sb.AppendLine($"                .Normal    = ColorHelper.MakeAttr(""{nfg}"", ""{nbg}""),")
                    sb.AppendLine($"                .Focus     = ColorHelper.MakeAttr(""{ffg}"", ""{fbg}""),")
                    sb.AppendLine($"                .Editable  = ColorHelper.MakeAttr(""{ffg}"", ""{fbg}""),")
                    sb.AppendLine($"                .HotNormal = ColorHelper.MakeAttr(""{nfg}"", ""{nbg}""),")
                    sb.AppendLine($"                .HotFocus  = ColorHelper.MakeAttr(""{ffg}"", ""{fbg}"")")
                    sb.AppendLine($"            }})")
                    sb.AppendLine($"            Me.Add({vn})")

                    ' Enforce max length and auto-advance to next field
                    sb.AppendLine($"            AddHandler {vn}.TextChanging, Sub(sender As Object, ev As ResultEventArgs(Of String))")
                    sb.AppendLine($"                If ev.Result IsNot Nothing AndAlso ev.Result.Length > {sfld.Len} Then")
                    sb.AppendLine($"                    ev.Result = ev.Result.Substring(0, {sfld.Len})")
                    sb.AppendLine($"                End If")
                    sb.AppendLine($"            End Sub")
                    sb.AppendLine($"            AddHandler {vn}.TextChanged, Sub(sender As Object, ev As EventArgs)")
                    sb.AppendLine($"                Dim fld = DirectCast(sender, TextField)")
                    sb.AppendLine($"                If fld.HasFocus AndAlso fld.Text IsNot Nothing AndAlso fld.Text.Length = {sfld.Len} Then")
                    sb.AppendLine($"                    fld.AdvanceFocus(NavigationDirection.Forward, TabBehavior.TabStop)")
                    sb.AppendLine($"                End If")
                    sb.AppendLine($"            End Sub")
                    sb.AppendLine()
                Next
            Next

            sb.AppendLine("            AddHandler Me.KeyDown, AddressOf OnKeyDown")
            sb.AppendLine("        End Sub")
            sb.AppendLine()

            ' Save handler — collects field values and writes a record
            sb.AppendLine("        ' Collect all field values, format them, and write to the data file.")
            sb.AppendLine("        Private Sub SaveRecord()")
            sb.AppendLine("            Dim rec As New System.Text.StringBuilder")
            varIdx = 0
            For Each scr In doc.Screens
                For Each sfld In scr.Fields
                    Dim vn = fieldVars(varIdx) : varIdx += 1
                    Dim maskRaw = sfld.ValidateFunc  ' use validate func name if set
                    Dim fmt = ""
                    ' Find format from record field definition
                    For Each r In doc.Data.Records
                        If String.Equals(r.Name, sfld.IntoRecord, StringComparison.OrdinalIgnoreCase) Then
                            For Each f In r.Fields
                                If String.Equals(f.Name, sfld.IntoField, StringComparison.OrdinalIgnoreCase) Then
                                    fmt = f.Format.Raw
                                End If
                            Next
                        End If
                    Next
                    Dim isNum = fmt.Replace("9", "").Replace("Z", "").Trim().Length = 0 AndAlso fmt.Length > 0
                    sb.AppendLine($"            ' {sfld.Label} → {sfld.IntoRecord}.{sfld.IntoField}")
                    sb.AppendLine($"            rec.Append(FormatHelper.ApplyMask(If({vn}.Text, """"), ""{EscapeString(fmt)}"", {sfld.Len}, {isNum.ToString().ToLower()}))")
                Next
            Next
            sb.AppendLine("            DataFile.WriteRecord(rec.ToString())")
            sb.AppendLine("            _recordIndex = -1   ' reset to new record after save")
            sb.AppendLine("        End Sub")
            sb.AppendLine()

            ' Key handler — using correct Terminal.Gui v2 Key API
            sb.AppendLine("        Private Shadows Sub OnKeyDown(sender As Object, e As Key)")
            sb.AppendLine("            ' F3 = Cancel (clear fields)")
            sb.AppendLine("            If e = Key.F3 Then")
            sb.AppendLine("                ClearFields()")
            sb.AppendLine("                Return")
            sb.AppendLine("            End If")
            sb.AppendLine("            ' F10 = Quit")
            sb.AppendLine("            If e = Key.F10 Then")
            sb.AppendLine("                _app.RequestStop()")
            sb.AppendLine("                Return")
            sb.AppendLine("            End If")
            sb.AppendLine("            ' Right Ctrl + R = Save")
            sb.AppendLine("            If e.IsCtrl AndAlso e.NoCtrl = Key.R Then")
            sb.AppendLine("                SaveRecord()")
            sb.AppendLine("                ClearFields()")
            sb.AppendLine("                Return")
            sb.AppendLine("            End If")
            sb.AppendLine("            ' Shift + PgUp/PgDn/Home/End = record navigation")
            sb.AppendLine("            If e.IsShift Then")
            sb.AppendLine("                Dim base_ = e.NoShift")
            sb.AppendLine("                If base_ = Key.PageUp   Then NavigateRecord(_recordIndex - 1)")
            sb.AppendLine("                If base_ = Key.PageDown Then NavigateRecord(_recordIndex + 1)")
            sb.AppendLine("                If base_ = Key.Home     Then NavigateRecord(0)")
            sb.AppendLine("                If base_ = Key.End      Then NavigateRecord(_records.Count - 1)")
            sb.AppendLine("            End If")
            sb.AppendLine("        End Sub")
            sb.AppendLine()

            ' Navigation
            sb.AppendLine("        Private Sub NavigateRecord(idx As Integer)")
            sb.AppendLine("            _records = DataFile.ReadAllRecords()")
            sb.AppendLine("            If idx < 0 OrElse idx >= _records.Count Then Return")
            sb.AppendLine("            _recordIndex = idx")
            sb.AppendLine("            PopulateFields(_records(idx))")
            sb.AppendLine("        End Sub")
            sb.AppendLine()

            ' Populate fields from a raw record string
            sb.AppendLine("        Private Sub PopulateFields(raw As String)")
            varIdx = 0
            Dim pos = 0
            For Each scr In doc.Screens
                For Each sfld In scr.Fields
                    Dim vn = fieldVars(varIdx) : varIdx += 1
                    ' Find field start/len from record definition
                    Dim fStart = pos
                    Dim fLen = sfld.Len
                    For Each r In doc.Data.Records
                        If String.Equals(r.Name, sfld.IntoRecord, StringComparison.OrdinalIgnoreCase) Then
                            For Each f In r.Fields
                                If String.Equals(f.Name, sfld.IntoField, StringComparison.OrdinalIgnoreCase) Then
                                    If f.Start > 0 Then fStart = f.Start - 1
                                    fLen = f.Len
                                End If
                            Next
                        End If
                    Next
                    sb.AppendLine($"            If raw.Length >= {fStart + fLen} Then {vn}.Text = raw.Substring({fStart}, {fLen}).TrimEnd()")
                    pos += fLen
                Next
            Next
            sb.AppendLine("        End Sub")
            sb.AppendLine()

            ' ClearFields
            sb.AppendLine("        Private Sub ClearFields()")
            For Each vn In fieldVars
                sb.AppendLine($"            {vn}.Text = """"")
            Next
            sb.AppendLine("        End Sub")
            sb.AppendLine()
            sb.AppendLine("    End Class")
            sb.AppendLine("End Namespace")
            Write(dir, "MainForm.vb", sb)
        End Sub

        ' ── Validation stubs ─────────────────────────────────────────────────

        Private Sub WriteValidationStubs(dir As String, ns As String, doc As DslDocument)
            Dim funcs As New HashSet(Of String)(StringComparer.OrdinalIgnoreCase)
            For Each scr In doc.Screens
                For Each sfld In scr.Fields
                    If Not String.IsNullOrEmpty(sfld.ValidateFunc) Then
                        funcs.Add(sfld.ValidateFunc)
                    End If
                Next
            Next
            If funcs.Count = 0 Then Return

            Dim sb As New StringBuilder
            sb.AppendLine("' ValidationFunctions — stub implementations for VALIDATE WITH functions.")
            sb.AppendLine("' Replace each function body with your real validation logic.")
            sb.AppendLine("' Return values: True = accept, False = reject, a String = replace field value.")
            sb.AppendLine()
            sb.AppendLine($"Namespace {ns}")
            sb.AppendLine("    Public Module ValidationFunctions")
            sb.AppendLine()
            For Each fn In funcs
                sb.AppendLine($"        ' TODO: Implement {fn}")
                sb.AppendLine($"        Public Function {fn}(value As String) As Object")
                sb.AppendLine($"            Return True  ' accept by default")
                sb.AppendLine($"        End Function")
                sb.AppendLine()
            Next
            sb.AppendLine("    End Module")
            sb.AppendLine("End Namespace")
            Write(dir, "ValidationFunctions.vb", sb)
        End Sub

        ' ── Utilities ─────────────────────────────────────────────────────────

        Private Sub Write(dir As String, filename As String, sb As StringBuilder)
            File.WriteAllText(Path.Combine(dir, filename), sb.ToString(), System.Text.Encoding.UTF8)
        End Sub

        Private Shared Function EscapeString(s As String) As String
            Return s.Replace("\", "\\").Replace("""", """""")
        End Function

        Private Shared Function MakeSafeName(s As String) As String
            If String.IsNullOrEmpty(s) Then Return "App"
            Dim sb As New StringBuilder
            For Each c In s
                If Char.IsLetterOrDigit(c) Then sb.Append(c) Else sb.Append("_"c)
            Next
            ' Ensure it doesn't start with a digit
            If sb.Length > 0 AndAlso Char.IsDigit(sb(0)) Then sb.Insert(0, "_"c)
            Return sb.ToString()
        End Function

        Private Shared Function LineEndingString(ending As LineEnding) As String
            Select Case ending
                Case LineEnding.CRLF : Return "\r\n"
                Case LineEnding.LF   : Return "\n"
                Case LineEnding.CR   : Return "\r"
                Case Else            : Return ""
            End Select
        End Function

    End Class

