' CodeGenerator — writes a complete VB.NET + Terminal.Gui project to outputDir.
' One method per output file; string templates are used for clarity.
Imports System.IO
Imports System.Text
Imports System.Collections.Generic


    Public Class CodeGenerator

        ''' <summary>Generate the full project into outputDir, creating it if needed.</summary>
        Public Sub GenerateProject(doc As DslDocument, outputDir As String)
            Try
                Directory.CreateDirectory(outputDir)
            Catch ex As Exception
                Throw New InvalidOperationException(
                    $"Cannot create output directory '{outputDir}': {ex.Message}", ex)
            End Try

            ' Derive a safe project name from the directory name
            Dim projName = MakeSafeName(IO.Path.GetFileName(outputDir.TrimEnd(IO.Path.DirectorySeparatorChar)))
            If String.IsNullOrEmpty(projName) Then projName = "DataEntryApp"

            WriteProjectFile(outputDir, projName)
            WriteProgram(outputDir, projName, doc)
            WriteDataFile(outputDir, projName, doc)
            WriteFormatHelper(outputDir, projName)
            WriteColorHelper(outputDir, projName)
            WriteMainForm(outputDir, projName, doc)
            WriteValidationStubs(outputDir, projName, doc)
        End Sub

        ' ── .vbproj ──────────────────────────────────────────────────────────

        Private Sub WriteProjectFile(dir As String, name As String)
            Dim sb As New StringBuilder
            sb.AppendLine("<Project Sdk=""Microsoft.NET.Sdk"">")
            sb.AppendLine("  <PropertyGroup>")
            sb.AppendLine("    <OutputType>Exe</OutputType>")
            sb.AppendLine($"    <RootNamespace>{name}</RootNamespace>")
            sb.AppendLine("    <TargetFramework>net10.0</TargetFramework>")
            sb.AppendLine("    <PublishSingleFile>true</PublishSingleFile>")
            sb.AppendLine("    <SelfContained>true</SelfContained>")
            sb.AppendLine("    <InvariantGlobalization>true</InvariantGlobalization>")
            sb.AppendLine("    <SuppressTrimAnalysisWarnings>true</SuppressTrimAnalysisWarnings>")
            sb.AppendLine("  </PropertyGroup>")
            sb.AppendLine("  <ItemGroup>")
            sb.AppendLine("    <PackageReference Include=""Terminal.Gui"" Version=""2.4.17"" />")
            sb.AppendLine("  </ItemGroup>")
            sb.AppendLine("</Project>")
            Write(dir, $"{name}.vbproj", sb)
        End Sub


        ' ── Program.vb ───────────────────────────────────────────────────────

        Private Sub WriteProgram(dir As String, ns As String, doc As DslDocument)
            Dim sb As New StringBuilder
            sb.AppendLine($"' Generated by DataEntry compiler.")
            sb.AppendLine($"Imports Terminal.Gui.App")
            sb.AppendLine()
            sb.AppendLine($"Namespace {ns}")
            sb.AppendLine($"    Module Program")
            sb.AppendLine($"        Sub Main(args As String())")
            sb.AppendLine($"            DataFile.Initialize()   ' handle NOAPPEND before any UI starts")
            sb.AppendLine($"            Dim app = Application.Create().Init()")
            sb.AppendLine($"            Dim form As New MainForm(app)")
            sb.AppendLine($"            app.Run(form, Nothing)")
            sb.AppendLine($"            app.Dispose()")
            sb.AppendLine($"        End Sub")
            sb.AppendLine($"    End Module")
            sb.AppendLine($"End Namespace")
            Write(dir, "Program.vb", sb)
        End Sub

        ' ── DataFile.vb ──────────────────────────────────────────────────────

        Private Sub WriteDataFile(dir As String, ns As String, doc As DslDocument)
            Dim ds      = doc.Data
            Dim lendExpr = LineEndingExpr(ds.Ending)   ' VB.NET expression: vbCrLf, vbLf, vbCr, or """"""
            Dim lendLen  = LineEndingLen(ds.Ending)    ' byte count (0–2) — known at code-gen time
            Dim recSize  = ds.Lrecl + lendLen          ' total bytes per record in the file
            Dim isAppend = (ds.Mode = AppendMode.Append)

            Dim sb As New StringBuilder
            sb.AppendLine("' DataFile — handles reading and writing fixed-length records.")
            sb.AppendLine("Imports System.IO")
            sb.AppendLine("Imports System.Text")
            sb.AppendLine()
            sb.AppendLine($"Namespace {ns}")
            sb.AppendLine("    Public Class DataFile")
            sb.AppendLine($"        Private Const FilePath As String = ""{EscapeString(ds.FilePath)}""")
            sb.AppendLine($"        Private Const Lrecl   As Integer = {ds.Lrecl}")
            sb.AppendLine($"        Private Const RecSize As Integer = {recSize}   ' Lrecl + line-ending bytes")
            sb.AppendLine()

            ' ── Initialize: honour NOAPPEND by deleting the output file at startup. ──
            ' WriteRecord always appends; the file starts fresh because Initialize deleted it.
            sb.AppendLine("        ''' <summary>")
            sb.AppendLine("        ''' Call once at startup before any record is written.")
            If isAppend Then
                sb.AppendLine("        ''' APPEND mode — existing records are preserved.")
            Else
                sb.AppendLine("        ''' NOAPPEND mode — deletes the output file so the session starts fresh.")
            End If
            sb.AppendLine("        ''' </summary>")
            sb.AppendLine("        Public Shared Sub Initialize()")
            If isAppend Then
                sb.AppendLine("            ' APPEND — nothing to do.")
            Else
                sb.AppendLine("            If File.Exists(FilePath) Then File.Delete(FilePath)")
            End If
            sb.AppendLine("        End Sub")
            sb.AppendLine()

            ' ── WriteRecord ──────────────────────────────────────────────────
            sb.AppendLine("        ''' <summary>Pad/truncate data to LRECL and append it to the output file.</summary>")
            sb.AppendLine("        Public Shared Sub WriteRecord(data As String)")
            sb.AppendLine("            SaveRecordAtIndex(-1, data)")
            sb.AppendLine("        End Sub")
            sb.AppendLine()
            sb.AppendLine("        ''' <summary>Save record at index (index >= 0 updates existing record; index < 0 appends).</summary>")
            sb.AppendLine("        Public Shared Sub SaveRecordAtIndex(index As Integer, data As String)")
            sb.AppendLine("            If data.Length < Lrecl Then data = data.PadRight(Lrecl)")
            sb.AppendLine("            If data.Length > Lrecl Then data = data.Substring(0, Lrecl)")
            sb.AppendLine("            Dim records = ReadAllRecords()")
            sb.AppendLine("            If index >= 0 AndAlso index < records.Count Then")
            sb.AppendLine("                records(index) = data")
            sb.AppendLine("                WriteAllRecords(records)")
            sb.AppendLine("            Else")
            sb.AppendLine("                Using sw As New StreamWriter(FilePath, append:=True, Encoding.ASCII)")
            sb.AppendLine("                    sw.Write(data)")
            If lendLen > 0 Then
                sb.AppendLine($"                    sw.Write({lendExpr})   ' {ds.Ending} line ending")
            End If
            sb.AppendLine("                End Using")
            sb.AppendLine("            End If")
            sb.AppendLine("        End Sub")
            sb.AppendLine()
            sb.AppendLine("        Private Shared Sub WriteAllRecords(records As List(Of String))")
            sb.AppendLine("            Using sw As New StreamWriter(FilePath, append:=False, Encoding.ASCII)")
            sb.AppendLine("                For Each rec In records")
            sb.AppendLine("                    Dim d = rec")
            sb.AppendLine("                    If d.Length < Lrecl Then d = d.PadRight(Lrecl)")
            sb.AppendLine("                    If d.Length > Lrecl Then d = d.Substring(0, Lrecl)")
            sb.AppendLine("                    sw.Write(d)")
            If lendLen > 0 Then
                sb.AppendLine($"                    sw.Write({lendExpr})")
            End If
            sb.AppendLine("                Next")
            sb.AppendLine("            End Using")
            sb.AppendLine("        End Sub")
            sb.AppendLine()
            sb.AppendLine("        ''' <summary>Read all fixed-length records from the file.</summary>")
            sb.AppendLine("        Public Shared Function ReadAllRecords() As List(Of String)")
            sb.AppendLine("            Dim records As New List(Of String)")
            sb.AppendLine("            If Not File.Exists(FilePath) Then Return records")
            sb.AppendLine("            Dim raw = File.ReadAllBytes(FilePath)")
            sb.AppendLine($"            Const recSize As Integer = {recSize}   ' Lrecl({ds.Lrecl}) + ending({lendLen})")
            sb.AppendLine("            Dim i = 0")
            sb.AppendLine("            Do While i + Lrecl <= raw.Length")
            sb.AppendLine("                records.Add(Encoding.ASCII.GetString(raw, i, Lrecl))")
            sb.AppendLine("                i += recSize")
            sb.AppendLine("            Loop")
            sb.AppendLine("            Return records")
            sb.AppendLine("        End Function")
            sb.AppendLine("    End Class")
            sb.AppendLine("End Namespace")
            Write(dir, "DataFile.vb", sb)
        End Sub

        ' ── FormatHelper.vb ──────────────────────────────────────────────────

        Private Sub WriteFormatHelper(dir As String, ns As String)
            Dim sb As New StringBuilder
            sb.AppendLine("' FormatHelper — applies FORMAT mask rules to field values.")
            sb.AppendLine("Imports System.Text")
            sb.AppendLine()
            sb.AppendLine($"Namespace {ns}")
            sb.AppendLine("    Public Module FormatHelper")
            sb.AppendLine()
            sb.AppendLine("        ' Apply a FORMAT mask to a raw input string.")
            sb.AppendLine("        ' Returns the formatted string padded/trimmed to fieldLen.")
            sb.AppendLine("        Public Function ApplyMask(raw As String, mask As String,")
            sb.AppendLine("                                  fieldLen As Integer,")
            sb.AppendLine("                                  isNumeric As Boolean) As String")
            sb.AppendLine("            ' No FORMAT mask — accept input verbatim, just pad/truncate to fieldLen.")
            sb.AppendLine("            If mask.Length = 0 Then")
            sb.AppendLine("                If raw.Length < fieldLen Then Return raw.PadRight(fieldLen)")
            sb.AppendLine("                If raw.Length > fieldLen Then Return raw.Substring(0, fieldLen)")
            sb.AppendLine("                Return raw")
            sb.AppendLine("            End If")
            sb.AppendLine()
            sb.AppendLine("            ' Decimal numeric mask check (contains pure 9/Z and exactly one '.' literal)")
            sb.AppendLine("            Dim isDecNum = False")
            sb.AppendLine("            Dim dotPos = -1")
            sb.AppendLine("            If IsNumericMask(mask) Then")
            sb.AppendLine("                Dim dotCnt = 0")
            sb.AppendLine("                Dim otherLitCnt = 0")
            sb.AppendLine("                Dim idx = 0")
            sb.AppendLine("                Do While idx < mask.Length")
            sb.AppendLine("                    If mask(idx) = ""\""c AndAlso idx + 1 < mask.Length Then")
            sb.AppendLine("                        If mask(idx + 1) = "".""c Then dotCnt += 1 : dotPos = idx Else otherLitCnt += 1")
            sb.AppendLine("                        idx += 2 : Continue Do")
            sb.AppendLine("                    ElseIf mask(idx) = "".""c Then")
            sb.AppendLine("                        dotCnt += 1 : dotPos = idx")
            sb.AppendLine("                    ElseIf mask(idx) <> ""9""c AndAlso mask(idx) <> ""Z""c Then")
            sb.AppendLine("                        otherLitCnt += 1")
            sb.AppendLine("                    End If")
            sb.AppendLine("                    idx += 1")
            sb.AppendLine("                Loop")
            sb.AppendLine("                If dotCnt = 1 AndAlso otherLitCnt = 0 AndAlso dotPos > 0 AndAlso dotPos < mask.Length - 1 Then")
            sb.AppendLine("                    isDecNum = True")
            sb.AppendLine("                End If")
            sb.AppendLine("            End If")
            sb.AppendLine()
            sb.AppendLine("            If isDecNum Then")
            sb.AppendLine("                Return ApplyDecimalNumeric(raw, mask, dotPos, fieldLen)")
            sb.AppendLine("            End If")
            sb.AppendLine()
            sb.AppendLine("            ' Pure integer numeric mask check (only 9/Z, no literals)")
            sb.AppendLine("            Dim isPureInt = IsNumericMask(mask) AndAlso Not mask.Contains(""\"") AndAlso Not mask.Contains(""."")")
            sb.AppendLine("            If isPureInt Then")
            sb.AppendLine("                Return ApplyPureInteger(raw, mask, fieldLen)")
            sb.AppendLine("            End If")
            sb.AppendLine()
            sb.AppendLine("            Return ApplyGeneral(raw, mask, fieldLen, isNumeric)")
            sb.AppendLine("        End Function")
            sb.AppendLine()
            sb.AppendLine("        Private Function ApplyDecimalNumeric(raw As String, mask As String, dotPos As Integer, fieldLen As Integer) As String")
            sb.AppendLine("            Dim maskBefore = mask.Substring(0, dotPos).Replace(""\""c, """")")
            sb.AppendLine("            Dim maskAfter = mask.Substring(dotPos + 1).Replace(""\""c, """")")
            sb.AppendLine("            Dim rawTrim = If(raw, """").Trim()")
            sb.AppendLine("            Dim rawInt As String = """"")
            sb.AppendLine("            Dim rawFrac As String = """"")
            sb.AppendLine("            If rawTrim.Contains("".""c) Then")
            sb.AppendLine("                Dim dIdx = rawTrim.IndexOf("".""c)")
            sb.AppendLine("                rawInt = rawTrim.Substring(0, dIdx)")
            sb.AppendLine("                rawFrac = rawTrim.Substring(dIdx + 1)")
            sb.AppendLine("            ElseIf rawTrim.Length > 0 Then")
            sb.AppendLine("                Dim totalDigits = maskBefore.Length + maskAfter.Length")
            sb.AppendLine("                If rawTrim.Length = totalDigits Then")
            sb.AppendLine("                    rawInt = rawTrim.Substring(0, maskBefore.Length)")
            sb.AppendLine("                    rawFrac = rawTrim.Substring(maskBefore.Length)")
            sb.AppendLine("                Else")
            sb.AppendLine("                    rawInt = rawTrim")
            sb.AppendLine("                    rawFrac = """"")
            sb.AppendLine("                End If")
            sb.AppendLine("            End If")
            sb.AppendLine("            Dim sbInt As New StringBuilder")
            sb.AppendLine("            For i = 0 To maskBefore.Length - 1")
            sb.AppendLine("                If i < maskBefore.Length - rawInt.Length Then")
            sb.AppendLine("                    sbInt.Append(If(maskBefore(i) = ""Z""c, ""0""c, "" ""c))")
            sb.AppendLine("                Else")
            sb.AppendLine("                    Dim ch = rawInt(i - (maskBefore.Length - rawInt.Length))")
            sb.AppendLine("                    If Char.IsDigit(ch) Then")
            sb.AppendLine("                        sbInt.Append(ch)")
            sb.AppendLine("                    ElseIf maskBefore(i) = ""Z""c Then")
            sb.AppendLine("                        sbInt.Append(""0""c)")
            sb.AppendLine("                    Else")
            sb.AppendLine("                        sbInt.Append("" ""c)")
            sb.AppendLine("                    End If")
            sb.AppendLine("                End If")
            sb.AppendLine("            Next")
            sb.AppendLine("            Dim sbFrac As New StringBuilder")
            sb.AppendLine("            For i = 0 To maskAfter.Length - 1")
            sb.AppendLine("                If i < rawFrac.Length AndAlso Char.IsDigit(rawFrac(i)) Then")
            sb.AppendLine("                    sbFrac.Append(rawFrac(i))")
            sb.AppendLine("                Else")
            sb.AppendLine("                    sbFrac.Append(""0""c)")
            sb.AppendLine("                End If")
            sb.AppendLine("            Next")
            sb.AppendLine("            Dim result = sbInt.ToString() & ""."" & sbFrac.ToString()")
            sb.AppendLine("            If result.Length < fieldLen Then Return result.PadLeft(fieldLen)")
            sb.AppendLine("            If result.Length > fieldLen Then Return result.Substring(0, fieldLen)")
            sb.AppendLine("            Return result")
            sb.AppendLine("        End Function")
            sb.AppendLine()
            sb.AppendLine("        Private Function ApplyPureInteger(raw As String, mask As String, fieldLen As Integer) As String")
            sb.AppendLine("            Dim rawTrim = If(raw, """").Trim()")
            sb.AppendLine("            If rawTrim.Contains("".""c) Then")
            sb.AppendLine("                rawTrim = rawTrim.Substring(0, rawTrim.IndexOf("".""c))")
            sb.AppendLine("            End If")
            sb.AppendLine("            Dim sb As New StringBuilder")
            sb.AppendLine("            For i = 0 To mask.Length - 1")
            sb.AppendLine("                If i < mask.Length - rawTrim.Length Then")
            sb.AppendLine("                    sb.Append(If(mask(i) = ""Z""c, ""0""c, "" ""c))")
            sb.AppendLine("                Else")
            sb.AppendLine("                    Dim ch = rawTrim(i - (mask.Length - rawTrim.Length))")
            sb.AppendLine("                    If Char.IsDigit(ch) Then")
            sb.AppendLine("                        sb.Append(ch)")
            sb.AppendLine("                    ElseIf mask(i) = ""Z""c Then")
            sb.AppendLine("                        sb.Append(""0""c)")
            sb.AppendLine("                    Else")
            sb.AppendLine("                        sb.Append("" ""c)")
            sb.AppendLine("                    End If")
            sb.AppendLine("                End If")
            sb.AppendLine("            Next")
            sb.AppendLine("            Dim result = sb.ToString()")
            sb.AppendLine("            If result.Length < fieldLen Then Return result.PadLeft(fieldLen)")
            sb.AppendLine("            If result.Length > fieldLen Then Return result.Substring(0, fieldLen)")
            sb.AppendLine("            Return result")
            sb.AppendLine("        End Function")
            sb.AppendLine()
            sb.AppendLine("        Private Function ApplyGeneral(raw As String, mask As String, fieldLen As Integer, isNumeric As Boolean) As String")
            sb.AppendLine("            raw = StripLiterals(raw, mask)")
            sb.AppendLine("            Dim sb As New StringBuilder")
            sb.AppendLine("            Dim ri = 0")
            sb.AppendLine("            Dim mi = 0")
            sb.AppendLine("            Do While mi < mask.Length")
            sb.AppendLine("                Dim mc = mask(mi)")
            sb.AppendLine("                If mc = ""\""c AndAlso mi + 1 < mask.Length Then")
            sb.AppendLine("                    sb.Append(mask(mi + 1))")
            sb.AppendLine("                    mi += 2")
            sb.AppendLine("                    Continue Do")
            sb.AppendLine("                End If")
            sb.AppendLine("                Select Case mc")
            sb.AppendLine("                    Case ""X""c : sb.Append(If(ri < raw.Length, raw(ri), "" ""c)) : ri += 1")
            sb.AppendLine("                    Case ""U""c : sb.Append(If(ri < raw.Length, Char.ToUpperInvariant(raw(ri)), "" ""c)) : ri += 1")
            sb.AppendLine("                    Case ""L""c : sb.Append(If(ri < raw.Length, Char.ToLowerInvariant(raw(ri)), "" ""c)) : ri += 1")
            sb.AppendLine("                    Case ""9""c : Dim dc = If(ri < raw.Length, raw(ri), "" ""c) : sb.Append(If(Char.IsDigit(dc), dc, "" ""c)) : ri += 1")
            sb.AppendLine("                    Case ""Z""c : Dim dc = If(ri < raw.Length, raw(ri), ""0""c) : sb.Append(If(Char.IsDigit(dc), dc, ""0""c)) : ri += 1")
            sb.AppendLine("                    Case Else : sb.Append(mc)")
            sb.AppendLine("                End Select")
            sb.AppendLine("                mi += 1")
            sb.AppendLine("            Loop")
            sb.AppendLine("            Dim result = sb.ToString()")
            sb.AppendLine("            If result.Length < fieldLen Then")
            sb.AppendLine("                result = If(isNumeric, result.PadLeft(fieldLen), result.PadRight(fieldLen))")
            sb.AppendLine("            ElseIf result.Length > fieldLen Then")
            sb.AppendLine("                result = result.Substring(0, fieldLen)")
            sb.AppendLine("            End If")
            sb.AppendLine("            Return result")
            sb.AppendLine("        End Function")
            sb.AppendLine()
            sb.AppendLine("        Private Function StripNonDigits(s As String) As String")
            sb.AppendLine("            If String.IsNullOrEmpty(s) Then Return """"")
            sb.AppendLine("            Dim sb As New StringBuilder(s.Length)")
            sb.AppendLine("            For Each ch In s")
            sb.AppendLine("                If Char.IsDigit(ch) Then sb.Append(ch)")
            sb.AppendLine("            Next")
            sb.AppendLine("            Return sb.ToString()")
            sb.AppendLine("        End Function")
            sb.AppendLine()
            sb.AppendLine("        Public Function StripLiterals(raw As String, mask As String) As String")
            sb.AppendLine("            If Not mask.Contains(""\"") Then Return raw")
            sb.AppendLine("            Dim hasAlphanumeric = False")
            sb.AppendLine("            Dim hasLetter = False")
            sb.AppendLine("            Dim hasDigit = False")
            sb.AppendLine("            Dim mi = 0")
            sb.AppendLine("            Do While mi < mask.Length")
            sb.AppendLine("                If mask(mi) = ""\""c AndAlso mi + 1 < mask.Length Then")
            sb.AppendLine("                    mi += 2 : Continue Do")
            sb.AppendLine("                End If")
            sb.AppendLine("                Select Case mask(mi)")
            sb.AppendLine("                    Case ""X""c : hasAlphanumeric = True")
            sb.AppendLine("                    Case ""U""c, ""L""c : hasLetter = True")
            sb.AppendLine("                    Case ""9""c, ""Z""c : hasDigit = True")
            sb.AppendLine("                End Select")
            sb.AppendLine("                mi += 1")
            sb.AppendLine("            Loop")
            sb.AppendLine("            If Not hasAlphanumeric AndAlso Not hasLetter AndAlso Not hasDigit Then Return raw")
            sb.AppendLine("            Dim result As New System.Text.StringBuilder(raw.Length)")
            sb.AppendLine("            For Each ch In raw")
            sb.AppendLine("                If hasAlphanumeric Then")
            sb.AppendLine("                    If Char.IsLetterOrDigit(ch) Then result.Append(ch)")
            sb.AppendLine("                ElseIf hasLetter Then")
            sb.AppendLine("                    If Char.IsLetter(ch) Then result.Append(ch)")
            sb.AppendLine("                ElseIf hasDigit Then")
            sb.AppendLine("                    If Char.IsDigit(ch) Then result.Append(ch)")
            sb.AppendLine("                End If")
            sb.AppendLine("            Next")
            sb.AppendLine("            Return result.ToString()")
            sb.AppendLine("        End Function")
            sb.AppendLine()
            sb.AppendLine("        Public Function IsNumericMask(mask As String) As Boolean")
            sb.AppendLine("            Dim i = 0")
            sb.AppendLine("            Dim hasDigitPlaceholder = False")
            sb.AppendLine("            Do While i < mask.Length")
            sb.AppendLine("                If mask(i) = ""\""c AndAlso i + 1 < mask.Length Then")
            sb.AppendLine("                    i += 2 : Continue Do")
            sb.AppendLine("                End If")
            sb.AppendLine("                If mask(i) = ""9""c OrElse mask(i) = ""Z""c Then")
            sb.AppendLine("                    hasDigitPlaceholder = True")
            sb.AppendLine("                ElseIf mask(i) = ""X""c OrElse mask(i) = ""U""c OrElse mask(i) = ""L""c Then")
            sb.AppendLine("                    Return False")
            sb.AppendLine("                End If")
            sb.AppendLine("                i += 1")
            sb.AppendLine("            Loop")
            sb.AppendLine("            Return hasDigitPlaceholder")
            sb.AppendLine("        End Function")
            sb.AppendLine()
            sb.AppendLine("    End Module")
            sb.AppendLine("End Namespace")
            sb.AppendLine()
            Write(dir, "FormatHelper.vb", sb)
        End Sub

        ' ── ColorHelper.vb (copy into generated project) ─────────────────────

        Private Sub WriteColorHelper(dir As String, ns As String)
            ' We regenerate a self-contained copy so the output project is stand-alone.
            Dim sb As New StringBuilder
            sb.AppendLine("' ColorHelper — maps color name strings to Terminal.Gui ColorName16.")
            sb.AppendLine("Imports Terminal.Gui.Drawing")
            sb.AppendLine()
            sb.AppendLine($"Namespace {ns}")
            sb.AppendLine("    Public Module ColorHelper")
            sb.AppendLine("        Public Function ToColorName16(name As String) As ColorName16")
            sb.AppendLine("            Select Case name.Trim().ToLowerInvariant()")
            sb.AppendLine("                Case ""black""        : Return ColorName16.Black")
            sb.AppendLine("                Case ""darkred"", ""red""  : Return ColorName16.Red")
            sb.AppendLine("                Case ""darkgreen"", ""green"" : Return ColorName16.Green")
            sb.AppendLine("                Case ""darkyellow"", ""yellow"" : Return ColorName16.Yellow")
            sb.AppendLine("                Case ""darkblue"", ""blue"" : Return ColorName16.Blue")
            sb.AppendLine("                Case ""darkmagenta"", ""magenta"" : Return ColorName16.Magenta")
            sb.AppendLine("                Case ""darkcyan"", ""cyan"" : Return ColorName16.Cyan")
            sb.AppendLine("                Case ""gray""         : Return ColorName16.Gray")
            sb.AppendLine("                Case ""darkgray""     : Return ColorName16.DarkGray")
            sb.AppendLine("                Case ""white""        : Return ColorName16.White")
            sb.AppendLine("                Case Else            : Return ColorName16.Gray")
            sb.AppendLine("            End Select")
            sb.AppendLine("        End Function")
            sb.AppendLine()
            sb.AppendLine("        Public Function MakeAttr(fg As String, bg As String) As Attribute")
            sb.AppendLine("            Return New Attribute(ToColorName16(fg), ToColorName16(bg))")
            sb.AppendLine("        End Function")
            sb.AppendLine("    End Module")
            sb.AppendLine("End Namespace")
            Write(dir, "ColorHelper.vb", sb)
        End Sub

        ' ── MainForm.vb ──────────────────────────────────────────────────────

        Private Sub WriteMainForm(dir As String, ns As String, doc As DslDocument)
            Dim sb As New StringBuilder
            sb.AppendLine("' MainForm — the generated data-entry form.")
            sb.AppendLine("Imports Terminal.Gui.App")
            sb.AppendLine("Imports Terminal.Gui.Views")
            sb.AppendLine("Imports Terminal.Gui.Drawing")
            sb.AppendLine("Imports Terminal.Gui.Input")
            sb.AppendLine("Imports Terminal.Gui.ViewBase")
            sb.AppendLine("Imports System.Collections.Generic")
            sb.AppendLine("Imports TPos = Terminal.Gui.ViewBase.Pos")
            sb.AppendLine("Imports TDim = Terminal.Gui.ViewBase.Dim")
            sb.AppendLine()
            sb.AppendLine($"Namespace {ns}")
            sb.AppendLine("    Public Class MainForm")
            sb.AppendLine("        Inherits Window")
            sb.AppendLine()

            ' One field per screen field — collect all fields across all screens
            Dim fieldVars As New List(Of String)
            For Each scr In doc.Screens
                For i = 0 To scr.Fields.Count - 1
                    Dim varName = $"_{MakeSafeName(scr.Name)}_{i}"
                    fieldVars.Add(varName)
                    sb.AppendLine($"        Private {varName} As TextField")
                Next
            Next

            sb.AppendLine()
            sb.AppendLine("        Private _app As IApplication")
            sb.AppendLine("        Private _recordIndex As Integer = -1")
            sb.AppendLine("        Private _records As List(Of String)")
            sb.AppendLine("        Private _allFields As New List(Of TextField)")
            sb.AppendLine("        Private _statusLabel As Label")
            Dim screenCount = doc.Screens.Count
            sb.AppendLine($"        Private _screenIndex As Integer = 0")
            sb.AppendLine($"        Private _screenViews({Math.Max(screenCount - 1, 0)}) As List(Of View)")
            ' Per-screen field lists (for rebuilding _allFields on screen switch)
            For si = 0 To screenCount - 1
                sb.AppendLine($"        Private _screenFields{si} As New List(Of TextField)")
            Next
            ' Per-screen title and scheme info (baked in at codegen time)
            For si = 0 To screenCount - 1
                Dim scrI = doc.Screens(si)
                sb.AppendLine($"        Private ReadOnly _screenTitle{si} As String = ""{EscapeString(scrI.Name)}""")
                sb.AppendLine($"        Private ReadOnly _screenFg{si} As String = ""{scrI.DefaultColor.Fg}""")
                sb.AppendLine($"        Private ReadOnly _screenBg{si} As String = ""{scrI.DefaultColor.Bg}""")
            Next
            sb.AppendLine()
            sb.AppendLine("        Public Sub New(app As IApplication)")
            sb.AppendLine("            _app = app")
            sb.AppendLine("            _records = DataFile.ReadAllRecords()")
            sb.AppendLine("            BuildForm()")
            sb.AppendLine("        End Sub")
            sb.AppendLine()
            sb.AppendLine("        Private Sub BuildForm()")

            ' Screen layout — only the very last field across ALL screens auto-saves on fill.
            Dim totalFieldCount = 0
            For Each scr In doc.Screens
                totalFieldCount += scr.Fields.Count
            Next

            Dim varIdx = 0
            Dim scrIdx = 0
            For Each scr In doc.Screens
                Dim nfgScr = scr.DefaultColor.Fg
                Dim nbgScr = scr.DefaultColor.Bg
                sb.AppendLine($"            ' ── Screen {scrIdx}: {scr.Name} ─────────────────────")
                sb.AppendLine($"            _screenViews({scrIdx}) = New List(Of View)()")
                sb.AppendLine()

                ' Standalone prompts
                Dim promptIdx = 0
                For Each pr In scr.Prompts
                    Dim pVar = $"_pr_{MakeSafeName(scr.Name)}_{promptIdx}"
                    promptIdx += 1
                    Dim pfg = If(pr.Color IsNot Nothing, pr.Color.Fg, scr.DefaultColor.Fg)
                    Dim pbg = If(pr.Color IsNot Nothing, pr.Color.Bg, scr.DefaultColor.Bg)
                    sb.AppendLine($"            ' Standalone Prompt: {EscapeString(pr.Text)}")
                    sb.AppendLine($"            Dim {pVar} As New Label()")
                    sb.AppendLine($"            {pVar}.Text  = ""{EscapeString(pr.Text)}""")
                    sb.AppendLine($"            {pVar}.X     = TPos.Absolute({pr.Col - 1})")
                    sb.AppendLine($"            {pVar}.Y     = TPos.Absolute({pr.Row})")
                    sb.AppendLine($"            {pVar}.Width = TDim.Auto()")
                    If pr.Color IsNot Nothing Then
                        sb.AppendLine($"            {pVar}.SetScheme(New Scheme With {{")
                        sb.AppendLine($"                .Normal    = ColorHelper.MakeAttr(""{pfg}"", ""{pbg}""),")
                        sb.AppendLine($"                .Focus     = ColorHelper.MakeAttr(""{pfg}"", ""{pbg}""),")
                        sb.AppendLine($"                .Editable  = ColorHelper.MakeAttr(""{pfg}"", ""{pbg}""),")
                        sb.AppendLine($"                .HotNormal = ColorHelper.MakeAttr(""{pfg}"", ""{pbg}""),")
                        sb.AppendLine($"                .HotFocus  = ColorHelper.MakeAttr(""{pfg}"", ""{pbg}"")")
                        sb.AppendLine($"            }})")
                    End If
                    sb.AppendLine($"            Me.Add({pVar})")
                    sb.AppendLine($"            _screenViews({scrIdx}).Add({pVar})")
                Next

                For Each sfld In scr.Fields
                    Dim vn = fieldVars(varIdx)
                    varIdx += 1
                    Dim isLastField = (varIdx = totalFieldCount)  ' only the very last field across all screens auto-saves
                    Dim nfg = If(sfld.NormalColor IsNot Nothing, sfld.NormalColor.Fg, scr.DefaultColor.Fg)
                    Dim nbg = If(sfld.NormalColor IsNot Nothing, sfld.NormalColor.Bg, scr.DefaultColor.Bg)
                    Dim ffg = If(sfld.FocusColor IsNot Nothing, sfld.FocusColor.Fg, "Black")
                    Dim fbg = If(sfld.FocusColor IsNot Nothing, sfld.FocusColor.Bg, "Cyan")

                    Dim fieldDescr = If(Not String.IsNullOrEmpty(sfld.Label), sfld.Label, $"{sfld.IntoRecord}.{sfld.IntoField}")
                    sb.AppendLine($"            ' Field: {EscapeString(fieldDescr)}")

                    Dim tf_x As Integer, tf_y As Integer
                    If Not String.IsNullOrEmpty(sfld.Label) Then
                        Dim pRow = If(sfld.PromptRow <> -1, sfld.PromptRow, sfld.Row)
                        Dim pCol = If(sfld.PromptCol <> -1, sfld.PromptCol, sfld.Col)
                        Dim lblVar = $"lbl_{vn.TrimStart("_"c)}"
                        sb.AppendLine($"            Dim {lblVar} As New Label()")
                        sb.AppendLine($"            {lblVar}.Text  = ""{EscapeString(sfld.Label)}:""")
                        sb.AppendLine($"            {lblVar}.X     = TPos.Absolute({pCol - 1})")
                        sb.AppendLine($"            {lblVar}.Y     = TPos.Absolute({pRow})")
                        sb.AppendLine($"            {lblVar}.Width = TDim.Auto()")
                        sb.AppendLine($"            Me.Add({lblVar})")

                        If sfld.PromptRow <> -1 AndAlso sfld.PromptCol <> -1 Then
                            tf_x = sfld.Col - 1
                            tf_y = sfld.Row
                        Else
                            tf_x = sfld.Col - 1 + sfld.Label.Length + 2
                            tf_y = sfld.Row
                        End If
                    Else
                        tf_x = sfld.Col - 1
                        tf_y = sfld.Row
                    End If

                    ' Compute hint from record field format tokens
                    Dim hintTokens As New List(Of MaskToken)
                    For Each r In doc.Data.Records
                        If String.Equals(r.Name, sfld.IntoRecord, StringComparison.OrdinalIgnoreCase) Then
                            For Each f In r.Fields
                                If String.Equals(f.Name, sfld.IntoField, StringComparison.OrdinalIgnoreCase) Then
                                    hintTokens = f.Format.Tokens
                                End If
                            Next
                        End If
                    Next
                    Dim hint = FormatMask.FormatHint(hintTokens)

                    sb.AppendLine($"            {vn} = New TextField()")
                    sb.AppendLine($"            {vn}.X     = TPos.Absolute({tf_x})")
                    sb.AppendLine($"            {vn}.Y     = TPos.Absolute({tf_y})")
                    sb.AppendLine($"            {vn}.Width = TDim.Absolute({sfld.Len})")
                    sb.AppendLine($"            {vn}.SetScheme(New Scheme With {{")
                    sb.AppendLine($"                .Normal    = ColorHelper.MakeAttr(""{nfg}"", ""{nbg}""),")
                    sb.AppendLine($"                .Focus     = ColorHelper.MakeAttr(""{ffg}"", ""{fbg}""),")
                    sb.AppendLine($"                .Editable  = ColorHelper.MakeAttr(""{ffg}"", ""{fbg}""),")
                    sb.AppendLine($"                .HotNormal = ColorHelper.MakeAttr(""{nfg}"", ""{nbg}""),")
                    sb.AppendLine($"                .HotFocus  = ColorHelper.MakeAttr(""{ffg}"", ""{fbg}"")")
                    sb.AppendLine($"            }})")
                    sb.AppendLine($"            Me.Add({vn})")
                    sb.AppendLine($"            _screenViews({scrIdx}).Add({vn})")
                    If sfld.IsProtected Then
                        sb.AppendLine($"            {vn}.ReadOnly = True")
                        sb.AppendLine($"            {vn}.TabStop  = False")
                    Else
                        sb.AppendLine($"            _screenFields{scrIdx}.Add({vn})")
                        sb.AppendLine($"            AddHandler {vn}.KeyDown, AddressOf OnKeyDown")
                    End If

                    ' Emit a muted hint label to the right of the field when the mask has embedded literals
                    If hint.Length > 0 Then
                        Dim hintVar = $"hint_{vn.TrimStart("_"c)}"
                        Dim hintX   = tf_x + sfld.Len + 1
                        sb.AppendLine($"            ' Format hint for {EscapeString(fieldDescr)}: {EscapeString(hint)}")
                        sb.AppendLine($"            Dim {hintVar} As New Label()")
                        sb.AppendLine($"            {hintVar}.Text  = ""{EscapeString(hint)}""")
                        sb.AppendLine($"            {hintVar}.X     = TPos.Absolute({hintX})")
                        sb.AppendLine($"            {hintVar}.Y     = TPos.Absolute({tf_y})")
                        sb.AppendLine($"            {hintVar}.Width = TDim.Auto()")
                        sb.AppendLine($"            {hintVar}.SetScheme(New Scheme With {{")
                        sb.AppendLine($"                .Normal    = ColorHelper.MakeAttr(""DarkGray"", ""{EscapeString(nbg)}""),")
                        sb.AppendLine($"                .Focus     = ColorHelper.MakeAttr(""DarkGray"", ""{EscapeString(nbg)}""),")
                        sb.AppendLine($"                .Editable  = ColorHelper.MakeAttr(""DarkGray"", ""{EscapeString(nbg)}""),")
                        sb.AppendLine($"                .HotNormal = ColorHelper.MakeAttr(""DarkGray"", ""{EscapeString(nbg)}""),")
                        sb.AppendLine($"                .HotFocus  = ColorHelper.MakeAttr(""DarkGray"", ""{EscapeString(nbg)}"")")
                        sb.AppendLine($"            }})")
                        sb.AppendLine($"            Me.Add({hintVar})")
                        sb.AppendLine($"            _screenViews({scrIdx}).Add({hintVar})")
                    End If

                    If Not sfld.IsProtected Then
                    ' Enforce max length — cancel the edit entirely when full to prevent Terminal.Gui
                    ' from advancing its internal ScrollOffset (which would shift text left).
                    sb.AppendLine($"            AddHandler {vn}.TextChanging, Sub(sender As Object, ev As ResultEventArgs(Of String))")
                    sb.AppendLine($"                If ev.Result IsNot Nothing AndAlso ev.Result.Length > {sfld.Len} Then")
                    sb.AppendLine($"                    ev.Result = DirectCast(sender, TextField).Text  ' cancel — keeps scroll offset stable")
                    sb.AppendLine($"                End If")
                    sb.AppendLine($"            End Sub")

                    If sfld.Full = FullBehavior.Stay Then
                        ' FULL=STAY — hold cursor at end, inhibit auto-advance/auto-save
                        sb.AppendLine($"            AddHandler {vn}.TextChanged, Sub(sender As Object, ev As EventArgs)")
                        sb.AppendLine($"                Dim fld = DirectCast(sender, TextField)")
                        sb.AppendLine($"                If fld.HasFocus AndAlso fld.Text IsNot Nothing AndAlso fld.Text.Length = {sfld.Len} Then")
                        sb.AppendLine($"                    fld.InsertionPoint = {sfld.Len - 1}  ' pin cursor at end, no advance")
                        sb.AppendLine($"                End If")
                        sb.AppendLine($"            End Sub")
                        sb.AppendLine($"            AddHandler {vn}.KeyDown, Sub(sender As Object, ev As Key)")
                        sb.AppendLine($"                If ev = Key.Enter Then")
                        sb.AppendLine($"                    Dim fld = DirectCast(sender, TextField)")
                        sb.AppendLine($"                    fld.SuperView?.AdvanceFocus(NavigationDirection.Forward, TabBehavior.TabStop)")
                        sb.AppendLine($"                    ev.Handled = True")
                        sb.AppendLine($"                End If")
                        sb.AppendLine($"            End Sub")
                    ElseIf isLastField Then
                        ' FULL=ADVANCE, last field — auto-save on completion
                        sb.AppendLine($"            AddHandler {vn}.TextChanged, Sub(sender As Object, ev As EventArgs)")
                        sb.AppendLine($"                Dim fld = DirectCast(sender, TextField)")
                        sb.AppendLine($"                If fld.HasFocus AndAlso fld.Text IsNot Nothing AndAlso fld.Text.Length = {sfld.Len} Then")
                        sb.AppendLine($"                    fld.InsertionPoint = 0")
                        sb.AppendLine($"                    fld.InsertionPoint = {sfld.Len - 1}")
                        sb.AppendLine($"                    SaveRecord()")
                        sb.AppendLine($"                    ClearFields()")
                        sb.AppendLine($"                End If")
                        sb.AppendLine($"            End Sub")
                        sb.AppendLine($"            AddHandler {vn}.KeyDown, Sub(sender As Object, ev As Key)")
                        sb.AppendLine($"                If ev = Key.Enter Then")
                        sb.AppendLine($"                    SaveRecord()")
                        sb.AppendLine($"                    ClearFields()")
                        sb.AppendLine($"                    ev.Handled = True")
                        sb.AppendLine($"                End If")
                        sb.AppendLine($"            End Sub")
                    Else
                        ' FULL=ADVANCE, intermediate field — auto-advance to next field
                        sb.AppendLine($"            AddHandler {vn}.TextChanged, Sub(sender As Object, ev As EventArgs)")
                        sb.AppendLine($"                Dim fld = DirectCast(sender, TextField)")
                        sb.AppendLine($"                If fld.HasFocus AndAlso fld.Text IsNot Nothing AndAlso fld.Text.Length = {sfld.Len} Then")
                        sb.AppendLine($"                    fld.InsertionPoint = 0")
                        sb.AppendLine($"                    fld.SuperView?.AdvanceFocus(NavigationDirection.Forward, TabBehavior.TabStop)")
                        sb.AppendLine($"                End If")
                        sb.AppendLine($"            End Sub")
                        sb.AppendLine($"            AddHandler {vn}.KeyDown, Sub(sender As Object, ev As Key)")
                        sb.AppendLine($"                If ev = Key.Enter Then")
                        sb.AppendLine($"                    Dim fld = DirectCast(sender, TextField)")
                        sb.AppendLine($"                    fld.SuperView?.AdvanceFocus(NavigationDirection.Forward, TabBehavior.TabStop)")
                        sb.AppendLine($"                    ev.Handled = True")
                        sb.AppendLine($"                End If")
                        sb.AppendLine($"            End Sub")
                    End If  ' Full behaviour

                    ' Validation Leave handler — fires when user leaves this field.
                    If Not String.IsNullOrEmpty(sfld.ValidateFunc) Then
                        ' Determine if this block needs the fields dictionary (cross-field Assign rule).
                        Dim blk As ValidateBlock = Nothing
                        For Each vblk In doc.ValidateBlocks
                            If String.Equals(vblk.Name, sfld.ValidateFunc, StringComparison.OrdinalIgnoreCase) Then
                                blk = vblk
                                Exit For
                            End If
                        Next
                        Dim needsFields = blk IsNot Nothing AndAlso
                            blk.Rules.Exists(Function(r) r.Kind = RuleKind.Assign)

                        Dim safeFn = MakeSafeName(sfld.ValidateFunc)
                        Dim efg = If(sfld.ErrorColor IsNot Nothing, sfld.ErrorColor.Fg, "White")
                        Dim ebg = If(sfld.ErrorColor IsNot Nothing, sfld.ErrorColor.Bg, "DarkRed")
                        Dim nfg2 = If(sfld.NormalColor IsNot Nothing, sfld.NormalColor.Fg, scr.DefaultColor.Fg)
                        Dim nbg2 = If(sfld.NormalColor IsNot Nothing, sfld.NormalColor.Bg, scr.DefaultColor.Bg)
                        Dim ffg2 = If(sfld.FocusColor IsNot Nothing, sfld.FocusColor.Fg, "Black")
                        Dim fbg2 = If(sfld.FocusColor IsNot Nothing, sfld.FocusColor.Bg, "Cyan")

                        sb.AppendLine($"            AddHandler {vn}.HasFocusChanging, Sub(sender As Object, ev As CancelEventArgs(Of Boolean))")
                        sb.AppendLine($"                If ev.NewValue Then Return  ' gaining focus — nothing to validate yet")
                        sb.AppendLine($"                Dim fld = DirectCast(sender, TextField)")
                        sb.AppendLine($"                Dim fieldVal = If(fld.Text, """")")

                        If needsFields Then
                            ' Build the fields dictionary from all named screen fields.
                            sb.AppendLine($"                Dim fldMap As New Dictionary(Of String, String)(StringComparer.OrdinalIgnoreCase)")
                            Dim di = 0
                            For Each dscr In doc.Screens
                                For Each dsfld In dscr.Fields
                                    sb.AppendLine($"                fldMap(""{dsfld.IntoField}"") = If({fieldVars(di)}.Text, """")")
                                    di += 1
                                Next
                            Next
                            sb.AppendLine($"                Dim vResult As Object = ValidationFunctions.{safeFn}(fieldVal, fldMap)")
                        Else
                            sb.AppendLine($"                Dim vResult As Object = ValidationFunctions.{safeFn}(fieldVal)")
                        End If

                        sb.AppendLine($"                Dim vBool As Boolean")
                        sb.AppendLine($"                Dim vStr As String = Nothing")
                        sb.AppendLine($"                If TypeOf vResult Is Boolean Then")
                        sb.AppendLine($"                    vBool = DirectCast(vResult, Boolean)")
                        sb.AppendLine($"                ElseIf vResult IsNot Nothing Then")
                        sb.AppendLine($"                    vStr = vResult.ToString()")
                        sb.AppendLine($"                    vBool = True")
                        sb.AppendLine($"                Else")
                        sb.AppendLine($"                    vBool = True")
                        sb.AppendLine($"                End If")
                        sb.AppendLine($"                If Not vBool Then")
                        sb.AppendLine($"                    ' Reject — show error colour and keep focus.")
                        sb.AppendLine($"                    fld.SetScheme(New Scheme With {{")
                        sb.AppendLine($"                        .Normal    = ColorHelper.MakeAttr(""{efg}"", ""{ebg}""),")
                        sb.AppendLine($"                        .Focus     = ColorHelper.MakeAttr(""{efg}"", ""{ebg}""),")
                        sb.AppendLine($"                        .Editable  = ColorHelper.MakeAttr(""{efg}"", ""{ebg}""),")
                        sb.AppendLine($"                        .HotNormal = ColorHelper.MakeAttr(""{efg}"", ""{ebg}""),")
                        sb.AppendLine($"                        .HotFocus  = ColorHelper.MakeAttr(""{efg}"", ""{ebg}"")")
                        sb.AppendLine($"                    }})")
                        sb.AppendLine($"                    If _statusLabel IsNot Nothing Then _statusLabel.Text = If(TypeOf vResult Is String, vResult.ToString(), ""Invalid value — please re-enter."")")
                        sb.AppendLine($"                    ev.Cancel = True  ' keep focus on this field")
                        sb.AppendLine($"                Else")
                        sb.AppendLine($"                    ' Accept — restore normal colour, clear status.")
                        sb.AppendLine($"                    fld.SetScheme(New Scheme With {{")
                        sb.AppendLine($"                        .Normal    = ColorHelper.MakeAttr(""{nfg2}"", ""{nbg2}""),")
                        sb.AppendLine($"                        .Focus     = ColorHelper.MakeAttr(""{ffg2}"", ""{fbg2}""),")
                        sb.AppendLine($"                        .Editable  = ColorHelper.MakeAttr(""{ffg2}"", ""{fbg2}""),")
                        sb.AppendLine($"                        .HotNormal = ColorHelper.MakeAttr(""{nfg2}"", ""{nbg2}""),")
                        sb.AppendLine($"                        .HotFocus  = ColorHelper.MakeAttr(""{ffg2}"", ""{fbg2}"")")
                        sb.AppendLine($"                    }})")
                        sb.AppendLine($"                    If _statusLabel IsNot Nothing Then _statusLabel.Text = """"")
                        If needsFields Then
                            Dim di2 = 0
                            For Each dscr In doc.Screens
                                For Each dsfld In dscr.Fields
                                    sb.AppendLine($"                    If fldMap.ContainsKey(""{dsfld.IntoField}"") AndAlso {fieldVars(di2)}.Text <> fldMap(""{dsfld.IntoField}"") Then {fieldVars(di2)}.Text = fldMap(""{dsfld.IntoField}"")")
                                    di2 += 1
                                Next
                            Next
                        Else
                            sb.AppendLine($"                    If vStr IsNot Nothing Then fld.Text = vStr")
                        End If
                        sb.AppendLine($"                End If")
                        sb.AppendLine($"            End Sub")
                    End If  ' ValidateFunc

                    End If  ' Not IsProtected

                    sb.AppendLine()
                Next
                scrIdx += 1
            Next

            ' After building all screens, hide screens 1+ (screen 0 is visible by default).
            For si = 1 To screenCount - 1
                sb.AppendLine($"            ' Hide screen {si} until PgDn switches to it.")
                sb.AppendLine($"            For Each v In _screenViews({si})")
                sb.AppendLine($"                v.Visible = False")
                sb.AppendLine($"            Next")
            Next

            ' Set initial title, scheme and _allFields from screen 0.
            If screenCount > 0 Then
                sb.AppendLine($"            Me.Title = _screenTitle0")
                sb.AppendLine($"            Me.SetScheme(New Scheme With {{")
                sb.AppendLine($"                .Normal    = ColorHelper.MakeAttr(_screenFg0, _screenBg0),")
                sb.AppendLine($"                .Focus     = ColorHelper.MakeAttr(""Black"", ""Cyan""),")
                sb.AppendLine($"                .Editable  = ColorHelper.MakeAttr(""Black"", ""Cyan""),")
                sb.AppendLine($"                .HotNormal = ColorHelper.MakeAttr(_screenFg0, _screenBg0),")
                sb.AppendLine($"                .HotFocus  = ColorHelper.MakeAttr(""Black"", ""Cyan"")")
                sb.AppendLine($"            }})")
                sb.AppendLine($"            _allFields.AddRange(_screenFields0)")
            End If

            ' Status label — shown at row 25 (below the 24-row screen area) for validation messages.
            sb.AppendLine("            _statusLabel = New Label()")
            sb.AppendLine("            _statusLabel.X     = TPos.Absolute(0)")
            sb.AppendLine("            _statusLabel.Y     = TPos.Absolute(25)")
            sb.AppendLine("            _statusLabel.Width = TDim.Fill()")
            sb.AppendLine("            _statusLabel.Text  = """"")
            sb.AppendLine("            Me.Add(_statusLabel)")

            sb.AppendLine("            AddHandler Me.KeyDown, AddressOf OnKeyDown")
            sb.AppendLine("        End Sub")
            sb.AppendLine()

            ' ShowScreen — only needed (and emitted) when the form has multiple screens.
            If screenCount > 1 Then
                sb.AppendLine("        Private Sub ShowScreen(idx As Integer)")
                sb.AppendLine($"            If idx < 0 OrElse idx >= {screenCount} Then Return")
                sb.AppendLine("            ' Hide all screen views.")
                For si = 0 To screenCount - 1
                    sb.AppendLine($"            For Each v In _screenViews({si})")
                    sb.AppendLine($"                v.Visible = False")
                    sb.AppendLine($"            Next")
                Next
                sb.AppendLine("            ' Show the requested screen's views.")
                sb.AppendLine("            For Each v In _screenViews(idx)")
                sb.AppendLine("                v.Visible = True")
                sb.AppendLine("            Next")
                sb.AppendLine("            _screenIndex = idx")
                sb.AppendLine("            ' Update title and colour scheme.")
                ' Build a Select Case for title/scheme by screen index
                sb.AppendLine("            Select Case idx")
                For si = 0 To screenCount - 1
                    sb.AppendLine($"                Case {si}")
                    sb.AppendLine($"                    Me.Title = _screenTitle{si}")
                    sb.AppendLine($"                    Me.SetScheme(New Scheme With {{")
                    sb.AppendLine($"                        .Normal    = ColorHelper.MakeAttr(_screenFg{si}, _screenBg{si}),")
                    sb.AppendLine($"                        .Focus     = ColorHelper.MakeAttr(""Black"", ""Cyan""),")
                    sb.AppendLine($"                        .Editable  = ColorHelper.MakeAttr(""Black"", ""Cyan""),")
                    sb.AppendLine($"                        .HotNormal = ColorHelper.MakeAttr(_screenFg{si}, _screenBg{si}),")
                    sb.AppendLine($"                        .HotFocus  = ColorHelper.MakeAttr(""Black"", ""Cyan"")")
                    sb.AppendLine($"                    }})")
                    sb.AppendLine($"                    _allFields.Clear()")
                    sb.AppendLine($"                    _allFields.AddRange(_screenFields{si})")
                Next
                sb.AppendLine("            End Select")
                sb.AppendLine("            ' Move focus to first field of new screen.")
                sb.AppendLine("            If _allFields.Count > 0 Then _allFields(0).SetFocus()")
                sb.AppendLine("            Me.SetNeedsDraw()")
                sb.AppendLine("        End Sub")
                sb.AppendLine()
            End If

            ' Save handler — collects field values and writes a record.
            ' Uses a fixed-width char buffer pre-filled with spaces so that dead space
            ' (gaps between fields with explicit START= positions) is preserved correctly.
            sb.AppendLine("        ' Collect all field values, format them, and write to the data file.")
            sb.AppendLine("        Private Sub SaveRecord()")
            sb.AppendLine($"            Dim buf({doc.Data.Lrecl - 1}) As Char")
            sb.AppendLine("            Array.Fill(buf, "" ""c)")
            varIdx = 0
            For Each scr In doc.Screens
                For Each sfld In scr.Fields
                    Dim vn = fieldVars(varIdx) : varIdx += 1
                    Dim fmt = ""
                    Dim fOffset = 0   ' 0-based buffer index (ResolvedStart - 1)
                    ' Find format and resolved position from record field definition.
                    For Each r In doc.Data.Records
                        If String.Equals(r.Name, sfld.IntoRecord, StringComparison.OrdinalIgnoreCase) Then
                            For Each f In r.Fields
                                If String.Equals(f.Name, sfld.IntoField, StringComparison.OrdinalIgnoreCase) Then
                                    fmt = f.Format.Raw
                                    fOffset = f.ResolvedStart - 1   ' convert 1-based → 0-based
                                End If
                            Next
                        End If
                    Next
                    ' Escape-aware numeric check: a mask is numeric if every non-escaped character is 9 or Z.
                    Dim isNum As Boolean = fmt.Length > 0
                    Dim ci = 0
                    Do While ci < fmt.Length
                        If fmt(ci) = "\"c AndAlso ci + 1 < fmt.Length Then
                            ci += 2  ' skip escaped literal — doesn't affect numeric classification
                        ElseIf fmt(ci) <> "9"c AndAlso fmt(ci) <> "Z"c Then
                            isNum = False
                            Exit Do
                        Else
                            ci += 1
                        End If
                    Loop
                    sb.AppendLine($"            ' {sfld.Label} → {sfld.IntoRecord}.{sfld.IntoField}")
                    sb.AppendLine($"            FormatHelper.ApplyMask(If({vn}.Text, """"), ""{EscapeString(fmt)}"", {sfld.Len}, {isNum.ToString().ToLower()}).CopyTo(0, buf, {fOffset}, {sfld.Len})")
                Next
            Next
            sb.AppendLine("            DataFile.SaveRecordAtIndex(_recordIndex, New String(buf))")
            sb.AppendLine("            _recordIndex = -1   ' reset to new record after save")
            sb.AppendLine("        End Sub")
            sb.AppendLine()

            ' Key handler — using correct Terminal.Gui v2 Key API
            sb.AppendLine("        Private Shadows Sub OnKeyDown(sender As Object, e As Key)")
            sb.AppendLine("            ' F1 = Help screen")
            sb.AppendLine("            If e = Key.F1 Then")
            sb.AppendLine("                ShowHelp()")
            sb.AppendLine("                e.Handled = True")
            sb.AppendLine("                Return")
            sb.AppendLine("            End If")
            sb.AppendLine("            ' F3 = Cancel (clear fields)")
            sb.AppendLine("            If e = Key.F3 Then")
            sb.AppendLine("                ClearFields()")
            sb.AppendLine("                e.Handled = True")
            sb.AppendLine("                Return")
            sb.AppendLine("            End If")
            sb.AppendLine("            ' F10 = Quit")
            sb.AppendLine("            If e = Key.F10 Then")
            sb.AppendLine("                _app.RequestStop()")
            sb.AppendLine("                e.Handled = True")
            sb.AppendLine("                Return")
            sb.AppendLine("            End If")
            sb.AppendLine("            ' Ctrl+S = Save record manually and clear fields")
            sb.AppendLine("            If e.IsCtrl AndAlso (e.NoCtrl = Key.S OrElse e.NoCtrl = Key.s) Then")
            sb.AppendLine("                SaveRecord()")
            sb.AppendLine("                ClearFields()")
            sb.AppendLine("                e.Handled = True")
            sb.AppendLine("                Return")
            sb.AppendLine("            End If")
            ' Only emit PgUp/PgDn screen-switching when there are multiple screens.
            If screenCount > 1 Then
                sb.AppendLine("            ' PgDn (unshifted) = next screen, PgUp (unshifted) = previous screen")
                sb.AppendLine("            If e = Key.PageDown AndAlso Not e.IsShift Then")
                sb.AppendLine($"                If _screenIndex < {screenCount - 1} Then ShowScreen(_screenIndex + 1)")
                sb.AppendLine("                e.Handled = True")
                sb.AppendLine("                Return")
                sb.AppendLine("            End If")
                sb.AppendLine("            If e = Key.PageUp AndAlso Not e.IsShift Then")
                sb.AppendLine("                If _screenIndex > 0 Then ShowScreen(_screenIndex - 1)")
                sb.AppendLine("                e.Handled = True")
                sb.AppendLine("                Return")
                sb.AppendLine("            End If")
            End If
            sb.AppendLine("            ' Shift + PgUp/PgDn/Home/End = record navigation")
            sb.AppendLine("            If e.IsShift Then")
            sb.AppendLine("                Dim base_ = e.NoShift")
            sb.AppendLine("                If base_ = Key.PageUp Then")
            sb.AppendLine("                    ' If no record loaded yet, go to last; otherwise go to previous.")
            sb.AppendLine("                    Dim prev = If(_recordIndex < 0, DataFile.ReadAllRecords().Count - 1, _recordIndex - 1)")
            sb.AppendLine("                    NavigateRecord(prev)")
            sb.AppendLine("                    e.Handled = True")
            sb.AppendLine("                End If")
            sb.AppendLine("                If base_ = Key.PageDown Then")
            sb.AppendLine("                    ' If no record loaded yet, go to first; otherwise go to next.")
            sb.AppendLine("                    Dim nxt = If(_recordIndex < 0, 0, _recordIndex + 1)")
            sb.AppendLine("                    NavigateRecord(nxt)")
            sb.AppendLine("                    e.Handled = True")
            sb.AppendLine("                End If")
            sb.AppendLine("                If base_ = Key.Home Then NavigateRecord(0) : e.Handled = True")
            sb.AppendLine("                If base_ = Key.End  Then")
            sb.AppendLine("                    ' Re-read count so we land on the true last record.")
            sb.AppendLine("                    NavigateRecord(DataFile.ReadAllRecords().Count - 1)")
            sb.AppendLine("                    e.Handled = True")
            sb.AppendLine("                End If")
            sb.AppendLine("            End If")
            sb.AppendLine("        End Sub")
            sb.AppendLine()
            sb.AppendLine("        Private Sub ShowHelp()")
            sb.AppendLine("            Dim helpMsg = ""Keyboard Shortcuts & Commands:"" & vbCrLf & vbCrLf & _")
            sb.AppendLine("                          ""  Enter / Tab      - Move to next field"" & vbCrLf & _")
            sb.AppendLine("                          ""  Shift+Tab        - Move to previous field"" & vbCrLf & _")
            sb.AppendLine("                          ""  Ctrl+S           - Save record"" & vbCrLf & _")
            sb.AppendLine("                          ""  F1               - Show this Help screen"" & vbCrLf & _")
            sb.AppendLine("                          ""  F3               - Cancel / Clear fields"" & vbCrLf & _")
            sb.AppendLine("                          ""  F10              - Quit application"" & vbCrLf & _")
            If screenCount > 1 Then
                sb.AppendLine("                          ""  PageDown         - Go to next screen"" & vbCrLf & _")
                sb.AppendLine("                          ""  PageUp           - Go to previous screen"" & vbCrLf & _")
            End If
            sb.AppendLine("                          ""  Shift + PageUp   - Go to previous record"" & vbCrLf & _")
            sb.AppendLine("                          ""  Shift + PageDown - Go to next record"" & vbCrLf & _")
            sb.AppendLine("                          ""  Shift + Home     - Go to first record"" & vbCrLf & _")
            sb.AppendLine("                          ""  Shift + End      - Go to last record""")
            sb.AppendLine("            MessageBox.Query(_app, ""Help — Commands & Hotkeys"", helpMsg, ""OK"")")
            sb.AppendLine("        End Sub")
            sb.AppendLine()

            ' Navigation
            sb.AppendLine("        Private Sub NavigateRecord(idx As Integer)")
            sb.AppendLine("            _records = DataFile.ReadAllRecords()")
            sb.AppendLine("            If idx < 0 OrElse idx >= _records.Count Then Return")
            sb.AppendLine("            _recordIndex = idx")
            sb.AppendLine("            PopulateFields(_records(idx))")
            sb.AppendLine("        End Sub")
            sb.AppendLine()

            ' Populate fields from a raw record string.
            ' Uses ResolvedStart (1-based) baked in at code-gen time so that both
            ' explicit START= fields and implicit sequential fields land at the correct offset.
            sb.AppendLine("        Private Sub PopulateFields(raw As String)")
            varIdx = 0
            For Each scr In doc.Screens
                For Each sfld In scr.Fields
                    Dim vn = fieldVars(varIdx) : varIdx += 1
                    ' Look up the resolved 1-based start and length from the record definition.
                    Dim fOffset = 0   ' 0-based Substring offset (ResolvedStart - 1)
                    Dim fLen = sfld.Len
                    For Each r In doc.Data.Records
                        If String.Equals(r.Name, sfld.IntoRecord, StringComparison.OrdinalIgnoreCase) Then
                            For Each f In r.Fields
                                If String.Equals(f.Name, sfld.IntoField, StringComparison.OrdinalIgnoreCase) Then
                                    fOffset = f.ResolvedStart - 1   ' convert 1-based → 0-based
                                    fLen = f.Len
                                End If
                            Next
                        End If
                    Next
                    sb.AppendLine($"            If raw.Length >= {fOffset + fLen} Then {vn}.Text = raw.Substring({fOffset}, {fLen}).TrimEnd()")
                Next
            Next
            sb.AppendLine("        End Sub")
            sb.AppendLine()

            ' ClearFields
            sb.AppendLine("        Private Sub ClearFields()")
            For Each vn In fieldVars
                sb.AppendLine($"            {vn}.Text = """"")
            Next
            sb.AppendLine("        End Sub")
            sb.AppendLine()
            sb.AppendLine("    End Class")
            sb.AppendLine("End Namespace")
            Write(dir, "MainForm.vb", sb)
        End Sub

        ' ── Validation stubs ─────────────────────────────────────────────────

        Private Sub WriteValidationStubs(dir As String, ns As String, doc As DslDocument)
            Dim funcs As New HashSet(Of String)(StringComparer.OrdinalIgnoreCase)
            For Each scr In doc.Screens
                For Each sfld In scr.Fields
                    If Not String.IsNullOrEmpty(sfld.ValidateFunc) Then
                        funcs.Add(sfld.ValidateFunc)
                    End If
                Next
            Next
            If funcs.Count = 0 AndAlso doc.ValidateBlocks.Count = 0 Then Return

            ' Build a lookup of defined blocks by name for O(1) access.
            Dim blockMap As New Dictionary(Of String, ValidateBlock)(StringComparer.OrdinalIgnoreCase)
            For Each blk In doc.ValidateBlocks
                blockMap(blk.Name) = blk
            Next
            ' Also ensure every block name is in the funcs set so it gets emitted.
            For Each blk In doc.ValidateBlocks
                funcs.Add(blk.Name)
            Next

            Dim sb As New StringBuilder
            sb.AppendLine("' ValidationFunctions — VALIDATE-SECTION compiled rules and stubs.")
            sb.AppendLine("' Functions with a body were generated from VALIDATE blocks in the .def file.")
            sb.AppendLine("' Functions marked TODO have no block defined — fill in your own logic.")
            sb.AppendLine("' Return values: True = accept, False = reject, a String = replace field value.")
            sb.AppendLine()
            sb.AppendLine($"Namespace {ns}")
            sb.AppendLine("    Public Module ValidationFunctions")
            sb.AppendLine()
            For Each fn In funcs
                Dim safeFn = MakeSafeName(fn)
                Dim blk As ValidateBlock = Nothing
                blockMap.TryGetValue(fn, blk)

                ' Determine if any rule in this block needs cross-field access or assignments.
                Dim needsFields = blk IsNot Nothing AndAlso
                    blk.Rules.Exists(Function(r) r.Kind = RuleKind.Assign)

                If needsFields Then
                    sb.AppendLine($"        Public Function {safeFn}(value As String, fields As System.Collections.Generic.Dictionary(Of String, String)) As Object")
                Else
                    sb.AppendLine($"        Public Function {safeFn}(value As String) As Object")
                End If

                If blk Is Nothing Then
                    sb.AppendLine($"            ' TODO: Implement {safeFn}")
                    sb.AppendLine($"            Return True  ' accept by default")
                Else
                    EmitValidateBlockBody(sb, blk)
                End If

                sb.AppendLine($"        End Function")
                sb.AppendLine()
            Next
            ' Emit the _ParseField helper if any compiled block uses arithmetic.
            Dim needsParseHelper = doc.ValidateBlocks.Exists(
                Function(b) b.Rules.Exists(Function(r) r.Kind = RuleKind.Assign))
            If needsParseHelper Then
                sb.AppendLine("        ' Internal helper: convert a field string to Double for arithmetic.")
                sb.AppendLine("        Private Function _ParseField(s As String) As Double")
                sb.AppendLine("            Dim v As Double")
                sb.AppendLine("            Return If(Double.TryParse(If(s, """").Trim(), System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, v), v, 0.0)")
                sb.AppendLine("        End Function")
                sb.AppendLine()
            End If
            sb.AppendLine("    End Module")
            sb.AppendLine("End Namespace")
            Write(dir, "ValidationFunctions.vb", sb)
        End Sub

        ''' <summary>Emit the VB body lines for a compiled VALIDATE block.</summary>
        Private Sub EmitValidateBlockBody(sb As StringBuilder, blk As ValidateBlock)
            sb.AppendLine("            Dim _lastAssign As String = Nothing")
            Dim assignIdx = 0
            For Each rule In blk.Rules
                Select Case rule.Kind

                    Case RuleKind.NotEmpty
                        If Not String.IsNullOrEmpty(rule.Message) Then
                            sb.AppendLine($"            ' {EscapeString(rule.Message)}")
                        End If
                        sb.AppendLine("            If String.IsNullOrWhiteSpace(value) Then")
                        If Not String.IsNullOrEmpty(rule.Message) Then
                            sb.AppendLine($"                Return ""{EscapeString(rule.Message)}""")
                        Else
                            sb.AppendLine("                Return False")
                        End If
                        sb.AppendLine("            End If")

                    Case RuleKind.Between
                        If Not String.IsNullOrEmpty(rule.Message) Then
                            sb.AppendLine($"            ' {EscapeString(rule.Message)}")
                        End If
                        sb.AppendLine("            Dim _n As Double")
                        sb.AppendLine($"            If Not Double.TryParse(If(value, """").Trim(), System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, _n) OrElse _n < {rule.LowBound} OrElse _n > {rule.HighBound} Then")
                        If Not String.IsNullOrEmpty(rule.Message) Then
                            sb.AppendLine($"                Return ""{EscapeString(rule.Message)}""")
                        Else
                            sb.AppendLine("                Return False")
                        End If
                        sb.AppendLine("            End If")

                    Case RuleKind.Assign
                        assignIdx += 1
                        ' Build a VB expression string from the token list.
                        Dim expr As New System.Text.StringBuilder
                        For Each tok In rule.Expression
                            Select Case tok.Kind
                                Case ExprToken.ExprTokenKind.Number
                                    expr.Append($"CDbl({tok.Value})")
                                Case ExprToken.ExprTokenKind.Op
                                    expr.Append($" {tok.Value} ")
                                Case ExprToken.ExprTokenKind.FieldName
                                    If String.Equals(tok.Value, "VALUE", StringComparison.OrdinalIgnoreCase) Then
                                        expr.Append("_ParseField(value)")
                                    Else
                                        expr.Append($"_ParseField(If(fields IsNot Nothing AndAlso fields.ContainsKey(""{tok.Value}""), fields(""{tok.Value}""), """"))")
                                    End If
                            End Select
                        Next
                        Dim resVar = $"_result_{assignIdx}"
                        sb.AppendLine($"            Dim {resVar} As Double = {expr}")
                        If Not String.Equals(rule.TargetField, "VALUE", StringComparison.OrdinalIgnoreCase) Then
                            sb.AppendLine($"            If fields IsNot Nothing Then fields(""{rule.TargetField}"") = {resVar}.ToString(""G"", System.Globalization.CultureInfo.InvariantCulture)")
                        End If
                        sb.AppendLine($"            _lastAssign = {resVar}.ToString(""G"", System.Globalization.CultureInfo.InvariantCulture)")

                End Select
            Next
            sb.AppendLine("            If _lastAssign IsNot Nothing Then Return _lastAssign")
            sb.AppendLine("            Return True")
        End Sub

        ' ── Utilities ─────────────────────────────────────────────────────────

        Private Sub Write(dir As String, filename As String, sb As StringBuilder)
            File.WriteAllText(IO.Path.Combine(dir, filename), sb.ToString(), System.Text.Encoding.UTF8)
        End Sub

        Private Shared Function EscapeString(s As String) As String
            ' Escape double-quotes for VB.NET string literals ("" is the VB escape for ").
            ' Strip bare CR/LF so literals are never multi-line.
            ' NOTE: backslash is NOT a VB string escape character — do not double it.
            '       The \ in FORMAT masks (e.g. 999\-9999) must be passed through verbatim
            '       so the ApplyMask runtime interpreter can recognise them.
            Return s.Replace("""", """""").Replace(vbCr, "").Replace(vbLf, "")
        End Function

        Private Shared Function MakeSafeName(s As String) As String
            If String.IsNullOrEmpty(s) Then Return "App"
            Dim sb As New StringBuilder
            For Each c In s
                If Char.IsLetterOrDigit(c) Then sb.Append(c) Else sb.Append("_"c)
            Next
            ' Ensure it doesn't start with a digit
            If sb.Length > 0 AndAlso Char.IsDigit(sb(0)) Then sb.Insert(0, "_"c)
            Return sb.ToString()
        End Function

        ''' <summary>
        ''' Returns the VB.NET expression for the line ending suitable for embedding
        ''' in generated source code (e.g. "vbCrLf" rather than raw CR+LF bytes).
        ''' </summary>
        Private Shared Function LineEndingExpr(ending As LineEnding) As String
            Select Case ending
                Case LineEnding.CRLF : Return "vbCrLf"
                Case LineEnding.LF   : Return "vbLf"
                Case LineEnding.CR   : Return "vbCr"
                Case Else            : Return """"""""
            End Select
        End Function

        ''' <summary>Returns the byte count of the line-ending sequence.</summary>
        Private Shared Function LineEndingLen(ending As LineEnding) As Integer
            Select Case ending
                Case LineEnding.CRLF : Return 2
                Case LineEnding.LF   : Return 1
                Case LineEnding.CR   : Return 1
                Case Else            : Return 0
            End Select
        End Function

    End Class

