<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DataEntry</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataEntry.Core\DataEntry.Core.vbproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\DataEntry.Tests\Samples\*.def" CopyToPublishDirectory="PreserveNewest" Link="Samples\%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
